---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start containerd
  ansible.builtin.systemd:
    name: containerd
    enabled: yes
    state: started

- name: Ensure kubelet service is enabled and started
  ansible.builtin.systemd:
    name: kubelet
    enabled: yes
    state: started
  
- name: Restart kubelet
  ansible.builtin.systemd:
    name: kubelet
    state: restarted